# docker-compose.yml

version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: chat_postgres
    environment:
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: chatPassword
      POSTGRES_DB: chat
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
